# Copyright 2025 Francisco F. Pinochet
# Copyright 2026 Fastcomcorp, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

defmodule ArmoricoreRealtimeWeb.Endpoint do
  @moduledoc """
  Phoenix endpoint configuration for Armoricore.

  Handles HTTP/HTTPS requests, WebSocket connections, and static file serving.
  Automatically configures SSL/TLS based on certificate availability in production.

  ## Features

  - **HTTP/HTTPS Support**: Automatic SSL configuration for production
  - **WebSocket Channels**: Real-time communication for chat, ArcRTC, and presence
  - **Static File Serving**: Optimized asset delivery with caching
  - **Security Headers**: Comprehensive security middleware stack
  - **Rate Limiting**: DDoS protection and abuse prevention
  - **CORS**: Cross-origin resource sharing configuration

  ## SSL Configuration

  SSL certificates are automatically detected and configured if available:
  - Certificate path: `SSL_CERT_PATH` environment variable
  - Private key path: `SSL_KEY_PATH` environment variable
  - CA bundle path: `SSL_CA_PATH` environment variable (optional)

  Supports Let's Encrypt, commercial certificates, and self-signed certificates.
  """
  use Phoenix.Endpoint, otp_app: :armoricore_realtime

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_armoricore_realtime_key",
    signing_salt: "xJgMWSN6",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  socket "/socket", ArmoricoreRealtimeWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :armoricore_realtime,
    gzip: not code_reloading?,
    only: ArmoricoreRealtimeWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # SECURITY: Limit request body size to prevent DoS attacks
  # 10MB for JSON, 100MB for multipart (file uploads)
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    length: 10_485_760,  # 10MB for JSON/urlencoded
    read_length: 1_048_576,  # 1MB chunks
    read_timeout: 15_000  # 15 seconds timeout

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  
  # SECURITY: Add secure HTTP headers
  plug :put_secure_browser_headers
  
  plug ArmoricoreRealtimeWeb.Router
  
  # SECURITY: Set secure browser headers to prevent common attacks
  defp put_secure_browser_headers(conn, _opts) do
    conn
    |> put_resp_header("x-content-type-options", "nosniff")
    |> put_resp_header("x-frame-options", "DENY")
    |> put_resp_header("x-xss-protection", "1; mode=block")
    |> put_resp_header("referrer-policy", "strict-origin-when-cross-origin")
    |> put_resp_header("permissions-policy", "geolocation=(), microphone=(), camera=()")
    # SECURITY: HSTS header - enforce HTTPS (1 year, include subdomains)
    |> put_resp_header("strict-transport-security", "max-age=31536000; includeSubDomains; preload")
    # Content-Security-Policy: Allow self, WebSocket connections, and inline styles for LiveView
    |> put_resp_header("content-security-policy", 
      "default-src 'self'; " <>
      "script-src 'self' 'unsafe-inline' 'unsafe-eval'; " <>  # unsafe-eval needed for LiveView
      "style-src 'self' 'unsafe-inline'; " <>
      "img-src 'self' data: https:; " <>
      "font-src 'self' data:; " <>
      "connect-src 'self' ws: wss:; " <>
      "frame-ancestors 'none'; " <>
      "base-uri 'self'; " <>
      "form-action 'self'")
  end
end
